language: go

go:
  - tip
  - 1.5

os:
  - linux
  - osx

install:
  - go get github.com/smartystreets/goconvey/convey
  - go get github.com/sloonz/go-maildir
  - go get github.com/Sirupsen/logrus
  - go get github.com/gopistolet/smtp/smtp
  - go get github.com/gopistolet/smtp/mta
  - go get github.com/gopistolet/gospf

script:
  - go test -v ./...